services:
  web-app:
    build:
      context: .
    ports:
      - "5433:5433"
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    extra_hosts:
      - "host.docker.internal:host-gateway"

    command: >
      python manage.py runserver 0.0.0.0:5433

    depends_on:
      - database

  database:
   image: postgres:14.6-alpine
   environment:
     - POSTGRES_DB=dbname
     - POSTGRES_USER=dbuser
     - POSTGRES_PASSWORD=pass